<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>14 Modelling | opeRate</title>
  <meta name="description" content="Apply your knowledge of the R programming language to real problems and tasks." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="14 Modelling | opeRate" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="cover.png" />
  <meta property="og:description" content="Apply your knowledge of the R programming language to real problems and tasks." />
  <meta name="github-repo" content="ARawles/opeRate" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="14 Modelling | opeRate" />
  
  <meta name="twitter:description" content="Apply your knowledge of the R programming language to real problems and tasks." />
  <meta name="twitter:image" content="cover.png" />

<meta name="author" content="Adam Rawles" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="plotting.html"/>
<link rel="next" href="machine-learning.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.6.1/grViz.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> opeRate</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#about-me"><i class="fa fa-check"></i><b>1.2</b> About Me</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#using-r"><i class="fa fa-check"></i><b>1.3</b> Using R</a></li>
</ul></li>
<li class="part"><span><b>I tidyverse</b></span></li>
<li class="chapter" data-level="2" data-path="tidyverse-introduction.html"><a href="tidyverse-introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="tidy-data.html"><a href="tidy-data.html"><i class="fa fa-check"></i><b>3</b> “Tidy” data</a><ul>
<li class="chapter" data-level="3.1" data-path="tidy-data.html"><a href="tidy-data.html#questions"><i class="fa fa-check"></i><b>3.1</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-pipe.html"><a href="the-pipe.html"><i class="fa fa-check"></i><b>4</b> The pipe (<code>%&gt;%</code>)</a><ul>
<li class="chapter" data-level="4.1" data-path="the-pipe.html"><a href="the-pipe.html#questions-1"><i class="fa fa-check"></i><b>4.1</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="quasiquotation.html"><a href="quasiquotation.html"><i class="fa fa-check"></i><b>5</b> Quasiquotation</a><ul>
<li class="chapter" data-level="5.1" data-path="quasiquotation.html"><a href="quasiquotation.html#tidyselect"><i class="fa fa-check"></i><b>5.1</b> tidyselect</a></li>
<li class="chapter" data-level="5.2" data-path="quasiquotation.html"><a href="quasiquotation.html#questions-2"><i class="fa fa-check"></i><b>5.2</b> Questions</a></li>
</ul></li>
<li class="part"><span><b>II Data Analysis</b></span></li>
<li class="chapter" data-level="6" data-path="da-intro.html"><a href="da-intro.html"><i class="fa fa-check"></i><b>6</b> Introduction</a></li>
<li class="chapter" data-level="7" data-path="loading.html"><a href="loading.html"><i class="fa fa-check"></i><b>7</b> Loading</a><ul>
<li class="chapter" data-level="7.1" data-path="loading.html"><a href="loading.html#rds"><i class="fa fa-check"></i><b>7.1</b> RDS</a><ul>
<li class="chapter" data-level="7.1.1" data-path="loading.html"><a href="loading.html#advantages"><i class="fa fa-check"></i><b>7.1.1</b> Advantages</a></li>
<li class="chapter" data-level="7.1.2" data-path="loading.html"><a href="loading.html#disadvantages"><i class="fa fa-check"></i><b>7.1.2</b> Disadvantages</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="loading.html"><a href="loading.html#csv"><i class="fa fa-check"></i><b>7.2</b> CSV</a><ul>
<li class="chapter" data-level="7.2.1" data-path="loading.html"><a href="loading.html#loading-csv-files"><i class="fa fa-check"></i><b>7.2.1</b> Loading CSV files</a></li>
<li class="chapter" data-level="7.2.2" data-path="loading.html"><a href="loading.html#advantages-1"><i class="fa fa-check"></i><b>7.2.2</b> Advantages</a></li>
<li class="chapter" data-level="7.2.3" data-path="loading.html"><a href="loading.html#disadvantages-1"><i class="fa fa-check"></i><b>7.2.3</b> Disadvantages</a></li>
<li class="chapter" data-level="7.2.4" data-path="loading.html"><a href="loading.html#other-delimited-files"><i class="fa fa-check"></i><b>7.2.4</b> Other delimited files</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="loading.html"><a href="loading.html#excel-files"><i class="fa fa-check"></i><b>7.3</b> Excel files</a><ul>
<li class="chapter" data-level="7.3.1" data-path="loading.html"><a href="loading.html#advantages-2"><i class="fa fa-check"></i><b>7.3.1</b> Advantages</a></li>
<li class="chapter" data-level="7.3.2" data-path="loading.html"><a href="loading.html#disadvantages-2"><i class="fa fa-check"></i><b>7.3.2</b> Disadvantages</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="loading.html"><a href="loading.html#web-based-apis"><i class="fa fa-check"></i><b>7.4</b> Web-based APIs</a><ul>
<li class="chapter" data-level="7.4.1" data-path="loading.html"><a href="loading.html#what-are-apis"><i class="fa fa-check"></i><b>7.4.1</b> What are APIs?</a></li>
<li class="chapter" data-level="7.4.2" data-path="loading.html"><a href="loading.html#accessing-apis-in-r"><i class="fa fa-check"></i><b>7.4.2</b> Accessing APIs in R</a></li>
<li class="chapter" data-level="7.4.3" data-path="loading.html"><a href="loading.html#bmrsr"><i class="fa fa-check"></i><b>7.4.3</b> BMRSr</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="loading.html"><a href="loading.html#databases"><i class="fa fa-check"></i><b>7.5</b> Databases</a><ul>
<li class="chapter" data-level="7.5.1" data-path="loading.html"><a href="loading.html#database-management-systems-and-odbc"><i class="fa fa-check"></i><b>7.5.1</b> Database Management Systems and ODBC</a></li>
<li class="chapter" data-level="7.5.2" data-path="loading.html"><a href="loading.html#connecting-with-the-odbc-package"><i class="fa fa-check"></i><b>7.5.2</b> Connecting with the <code>odbc</code> package</a></li>
<li class="chapter" data-level="7.5.3" data-path="loading.html"><a href="loading.html#querying-the-database"><i class="fa fa-check"></i><b>7.5.3</b> Querying the database</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="cleaning.html"><a href="cleaning.html"><i class="fa fa-check"></i><b>8</b> Cleaning</a><ul>
<li class="chapter" data-level="8.1" data-path="cleaning.html"><a href="cleaning.html#filtering"><i class="fa fa-check"></i><b>8.1</b> Filtering</a></li>
<li class="chapter" data-level="8.2" data-path="cleaning.html"><a href="cleaning.html#missing-values"><i class="fa fa-check"></i><b>8.2</b> Missing values</a></li>
<li class="chapter" data-level="8.3" data-path="cleaning.html"><a href="cleaning.html#changing-column-types"><i class="fa fa-check"></i><b>8.3</b> Changing column types</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tidying.html"><a href="tidying.html"><i class="fa fa-check"></i><b>9</b> Tidying</a><ul>
<li class="chapter" data-level="9.1" data-path="tidying.html"><a href="tidying.html#pivoting"><i class="fa fa-check"></i><b>9.1</b> Pivoting</a><ul>
<li class="chapter" data-level="9.1.1" data-path="tidying.html"><a href="tidying.html#pivoting-columns-to-rows-longer"><i class="fa fa-check"></i><b>9.1.1</b> Pivoting columns to rows (longer)</a></li>
<li class="chapter" data-level="9.1.2" data-path="tidying.html"><a href="tidying.html#pivoting-rows-to-columns-wider"><i class="fa fa-check"></i><b>9.1.2</b> Pivoting rows to columns (wider)</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="tidying.html"><a href="tidying.html#separating-uniting"><i class="fa fa-check"></i><b>9.2</b> Separating &amp; Uniting</a><ul>
<li class="chapter" data-level="9.2.1" data-path="tidying.html"><a href="tidying.html#separating"><i class="fa fa-check"></i><b>9.2.1</b> Separating</a></li>
<li class="chapter" data-level="9.2.2" data-path="tidying.html"><a href="tidying.html#uniting"><i class="fa fa-check"></i><b>9.2.2</b> Uniting</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="grouping.html"><a href="grouping.html"><i class="fa fa-check"></i><b>10</b> Grouping</a></li>
<li class="chapter" data-level="11" data-path="mutating.html"><a href="mutating.html"><i class="fa fa-check"></i><b>11</b> Mutating</a></li>
<li class="chapter" data-level="12" data-path="summarising.html"><a href="summarising.html"><i class="fa fa-check"></i><b>12</b> Summarising</a></li>
<li class="chapter" data-level="13" data-path="plotting.html"><a href="plotting.html"><i class="fa fa-check"></i><b>13</b> Plotting</a><ul>
<li class="chapter" data-level="13.1" data-path="plotting.html"><a href="plotting.html#ggplot2"><i class="fa fa-check"></i><b>13.1</b> ggplot2</a><ul>
<li class="chapter" data-level="13.1.1" data-path="plotting.html"><a href="plotting.html#components"><i class="fa fa-check"></i><b>13.1.1</b> Components</a></li>
<li class="chapter" data-level="13.1.2" data-path="plotting.html"><a href="plotting.html#layers"><i class="fa fa-check"></i><b>13.1.2</b> Layers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="modelling.html"><a href="modelling.html"><i class="fa fa-check"></i><b>14</b> Modelling</a><ul>
<li class="chapter" data-level="14.1" data-path="modelling.html"><a href="modelling.html#types-of-model"><i class="fa fa-check"></i><b>14.1</b> Types of model</a><ul>
<li class="chapter" data-level="14.1.1" data-path="modelling.html"><a href="modelling.html#linear-models"><i class="fa fa-check"></i><b>14.1.1</b> Linear models</a></li>
<li class="chapter" data-level="14.1.2" data-path="modelling.html"><a href="modelling.html#quadratic"><i class="fa fa-check"></i><b>14.1.2</b> Quadratic</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="modelling.html"><a href="modelling.html#coefficients"><i class="fa fa-check"></i><b>14.2</b> Coefficients</a></li>
<li class="chapter" data-level="14.3" data-path="modelling.html"><a href="modelling.html#residuals"><i class="fa fa-check"></i><b>14.3</b> Residuals</a></li>
<li class="chapter" data-level="14.4" data-path="modelling.html"><a href="modelling.html#lm"><i class="fa fa-check"></i><b>14.4</b> <code>lm()</code></a></li>
<li class="chapter" data-level="14.5" data-path="modelling.html"><a href="modelling.html#multiple-predictors"><i class="fa fa-check"></i><b>14.5</b> Multiple Predictors</a><ul>
<li class="chapter" data-level="14.5.1" data-path="modelling.html"><a href="modelling.html#simple-effects"><i class="fa fa-check"></i><b>14.5.1</b> Simple effects</a></li>
<li class="chapter" data-level="14.5.2" data-path="modelling.html"><a href="modelling.html#interaction-effects"><i class="fa fa-check"></i><b>14.5.2</b> Interaction effects</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="modelling.html"><a href="modelling.html#evaluating-models"><i class="fa fa-check"></i><b>14.6</b> Evaluating Models</a><ul>
<li class="chapter" data-level="14.6.1" data-path="modelling.html"><a href="modelling.html#lm-output"><i class="fa fa-check"></i><b>14.6.1</b> <code>lm()</code> Output</a></li>
<li class="chapter" data-level="14.6.2" data-path="modelling.html"><a href="modelling.html#residuals-1"><i class="fa fa-check"></i><b>14.6.2</b> Residuals</a></li>
<li class="chapter" data-level="14.6.3" data-path="modelling.html"><a href="modelling.html#overfitting"><i class="fa fa-check"></i><b>14.6.3</b> Overfitting</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="modelling.html"><a href="modelling.html#video-game-sales-model"><i class="fa fa-check"></i><b>14.7</b> Video Game Sales Model</a><ul>
<li class="chapter" data-level="14.7.1" data-path="modelling.html"><a href="modelling.html#predicting-the-future"><i class="fa fa-check"></i><b>14.7.1</b> Predicting the future</a></li>
</ul></li>
<li class="chapter" data-level="14.8" data-path="modelling.html"><a href="modelling.html#questions-3"><i class="fa fa-check"></i><b>14.8</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="machine-learning.html"><a href="machine-learning.html"><i class="fa fa-check"></i><b>15</b> Machine Learning</a><ul>
<li class="chapter" data-level="15.1" data-path="machine-learning.html"><a href="machine-learning.html#neural-networks"><i class="fa fa-check"></i><b>15.1</b> Neural networks</a><ul>
<li class="chapter" data-level="15.1.1" data-path="machine-learning.html"><a href="machine-learning.html#introduction"><i class="fa fa-check"></i><b>15.1.1</b> Introduction</a></li>
<li class="chapter" data-level="15.1.2" data-path="machine-learning.html"><a href="machine-learning.html#example"><i class="fa fa-check"></i><b>15.1.2</b> Example</a></li>
<li class="chapter" data-level="15.1.3" data-path="machine-learning.html"><a href="machine-learning.html#neural-networks-in-r"><i class="fa fa-check"></i><b>15.1.3</b> Neural Networks in R</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Projects</b></span></li>
<li class="chapter" data-level="16" data-path="projects-introduction.html"><a href="projects-introduction.html"><i class="fa fa-check"></i><b>16</b> Introduction</a></li>
<li class="chapter" data-level="17" data-path="workflows.html"><a href="workflows.html"><i class="fa fa-check"></i><b>17</b> Workflows</a><ul>
<li class="chapter" data-level="17.1" data-path="workflows.html"><a href="workflows.html#basic-workflow"><i class="fa fa-check"></i><b>17.1</b> Basic Workflow</a><ul>
<li class="chapter" data-level="17.1.1" data-path="workflows.html"><a href="workflows.html#example-1-reporting"><i class="fa fa-check"></i><b>17.1.1</b> Example 1: Reporting</a></li>
<li class="chapter" data-level="17.1.2" data-path="workflows.html"><a href="workflows.html#example-2-modelling"><i class="fa fa-check"></i><b>17.1.2</b> Example 2: Modelling</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="workflows.html"><a href="workflows.html#separating-stages"><i class="fa fa-check"></i><b>17.2</b> Separating Stages</a><ul>
<li class="chapter" data-level="17.2.1" data-path="workflows.html"><a href="workflows.html#functions"><i class="fa fa-check"></i><b>17.2.1</b> Functions</a></li>
<li class="chapter" data-level="17.2.2" data-path="workflows.html"><a href="workflows.html#files"><i class="fa fa-check"></i><b>17.2.2</b> Files</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="workflows.html"><a href="workflows.html#summary"><i class="fa fa-check"></i><b>17.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="replicability.html"><a href="replicability.html"><i class="fa fa-check"></i><b>18</b> Replicability</a><ul>
<li class="chapter" data-level="18.1" data-path="replicability.html"><a href="replicability.html#good-practice"><i class="fa fa-check"></i><b>18.1</b> Good practice</a><ul>
<li class="chapter" data-level="18.1.1" data-path="replicability.html"><a href="replicability.html#use-a-consistent-naming-convention"><i class="fa fa-check"></i><b>18.1.1</b> Use a consistent naming convention</a></li>
<li class="chapter" data-level="18.1.2" data-path="replicability.html"><a href="replicability.html#name-your-variables-as-nouns-and-your-functions-as-verbs"><i class="fa fa-check"></i><b>18.1.2</b> Name your variables as nouns and your functions as verbs</a></li>
<li class="chapter" data-level="18.1.3" data-path="replicability.html"><a href="replicability.html#use-functions-where-you-can"><i class="fa fa-check"></i><b>18.1.3</b> Use functions where you can</a></li>
<li class="chapter" data-level="18.1.4" data-path="replicability.html"><a href="replicability.html#state-your-dependencies"><i class="fa fa-check"></i><b>18.1.4</b> State your dependencies</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="replicability.html"><a href="replicability.html#documentation"><i class="fa fa-check"></i><b>18.2</b> Documentation</a><ul>
<li class="chapter" data-level="18.2.1" data-path="replicability.html"><a href="replicability.html#function-documentation"><i class="fa fa-check"></i><b>18.2.1</b> Function documentation</a></li>
<li class="chapter" data-level="18.2.2" data-path="replicability.html"><a href="replicability.html#long-form-documentation"><i class="fa fa-check"></i><b>18.2.2</b> Long-form documentation</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="replicability.html"><a href="replicability.html#testing"><i class="fa fa-check"></i><b>18.3</b> Testing</a><ul>
<li class="chapter" data-level="18.3.1" data-path="replicability.html"><a href="replicability.html#testthat"><i class="fa fa-check"></i><b>18.3.1</b> <code>{testthat}</code></a></li>
<li class="chapter" data-level="18.3.2" data-path="replicability.html"><a href="replicability.html#defensive-programming"><i class="fa fa-check"></i><b>18.3.2</b> Defensive programming</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="projects-as-packages.html"><a href="projects-as-packages.html"><i class="fa fa-check"></i><b>19</b> Projects as Packages</a><ul>
<li class="chapter" data-level="19.1" data-path="projects-as-packages.html"><a href="projects-as-packages.html#structure"><i class="fa fa-check"></i><b>19.1</b> Structure</a><ul>
<li class="chapter" data-level="19.1.1" data-path="projects-as-packages.html"><a href="projects-as-packages.html#r-code"><i class="fa fa-check"></i><b>19.1.1</b> R code</a></li>
<li class="chapter" data-level="19.1.2" data-path="projects-as-packages.html"><a href="projects-as-packages.html#data"><i class="fa fa-check"></i><b>19.1.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="projects-as-packages.html"><a href="projects-as-packages.html#documentation-1"><i class="fa fa-check"></i><b>19.2</b> Documentation</a><ul>
<li class="chapter" data-level="19.2.1" data-path="projects-as-packages.html"><a href="projects-as-packages.html#functional"><i class="fa fa-check"></i><b>19.2.1</b> Functional</a></li>
<li class="chapter" data-level="19.2.2" data-path="projects-as-packages.html"><a href="projects-as-packages.html#long-form"><i class="fa fa-check"></i><b>19.2.2</b> Long-form</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="projects-as-packages.html"><a href="projects-as-packages.html#description"><i class="fa fa-check"></i><b>19.3</b> DESCRIPTION</a><ul>
<li class="chapter" data-level="19.3.1" data-path="projects-as-packages.html"><a href="projects-as-packages.html#dependencies"><i class="fa fa-check"></i><b>19.3.1</b> Dependencies</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="projects-as-packages.html"><a href="projects-as-packages.html#abstraction"><i class="fa fa-check"></i><b>19.4</b> Abstraction</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="git-github.html"><a href="git-github.html"><i class="fa fa-check"></i><b>20</b> Git &amp; GitHub</a><ul>
<li class="chapter" data-level="20.1" data-path="git-github.html"><a href="git-github.html#git"><i class="fa fa-check"></i><b>20.1</b> Git</a><ul>
<li class="chapter" data-level="20.1.1" data-path="git-github.html"><a href="git-github.html#repositories"><i class="fa fa-check"></i><b>20.1.1</b> Repositories</a></li>
<li class="chapter" data-level="20.1.2" data-path="git-github.html"><a href="git-github.html#commits"><i class="fa fa-check"></i><b>20.1.2</b> Commits</a></li>
<li class="chapter" data-level="20.1.3" data-path="git-github.html"><a href="git-github.html#pushing-pulling"><i class="fa fa-check"></i><b>20.1.3</b> Pushing &amp; Pulling</a></li>
<li class="chapter" data-level="20.1.4" data-path="git-github.html"><a href="git-github.html#branches"><i class="fa fa-check"></i><b>20.1.4</b> Branches</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="git-github.html"><a href="git-github.html#github"><i class="fa fa-check"></i><b>20.2</b> GitHub</a><ul>
<li class="chapter" data-level="20.2.1" data-path="git-github.html"><a href="git-github.html#forking"><i class="fa fa-check"></i><b>20.2.1</b> Forking</a></li>
<li class="chapter" data-level="20.2.2" data-path="git-github.html"><a href="git-github.html#pull-requests"><i class="fa fa-check"></i><b>20.2.2</b> Pull Requests</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="git-github.html"><a href="git-github.html#git-github-rstudio"><i class="fa fa-check"></i><b>20.3</b> Git, GitHub &amp; RStudio</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="project-example.html"><a href="project-example.html"><i class="fa fa-check"></i><b>21</b> Project Example</a><ul>
<li class="chapter" data-level="21.1" data-path="project-example.html"><a href="project-example.html#github-repository"><i class="fa fa-check"></i><b>21.1</b> GitHub Repository</a></li>
<li class="chapter" data-level="21.2" data-path="project-example.html"><a href="project-example.html#rstudio-project"><i class="fa fa-check"></i><b>21.2</b> RStudio Project</a></li>
<li class="chapter" data-level="21.3" data-path="project-example.html"><a href="project-example.html#description-1"><i class="fa fa-check"></i><b>21.3</b> DESCRIPTION</a></li>
<li class="chapter" data-level="21.4" data-path="project-example.html"><a href="project-example.html#data-1"><i class="fa fa-check"></i><b>21.4</b> Data</a></li>
<li class="chapter" data-level="21.5" data-path="project-example.html"><a href="project-example.html#structure-1"><i class="fa fa-check"></i><b>21.5</b> Structure</a></li>
<li class="chapter" data-level="21.6" data-path="project-example.html"><a href="project-example.html#documentation-2"><i class="fa fa-check"></i><b>21.6</b> Documentation</a><ul>
<li class="chapter" data-level="21.6.1" data-path="project-example.html"><a href="project-example.html#function"><i class="fa fa-check"></i><b>21.6.1</b> Function</a></li>
<li class="chapter" data-level="21.6.2" data-path="project-example.html"><a href="project-example.html#data-2"><i class="fa fa-check"></i><b>21.6.2</b> Data</a></li>
<li class="chapter" data-level="21.6.3" data-path="project-example.html"><a href="project-example.html#readme-vignettes"><i class="fa fa-check"></i><b>21.6.3</b> README &amp; Vignettes</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Question Answers</b></span></li>
<li class="chapter" data-level="22" data-path="answers.html"><a href="answers.html"><i class="fa fa-check"></i><b>22</b> Answers</a><ul>
<li class="chapter" data-level="22.1" data-path="answers.html"><a href="answers.html#tidy-data-1"><i class="fa fa-check"></i><b>22.1</b> “Tidy” data</a></li>
<li class="chapter" data-level="22.2" data-path="answers.html"><a href="answers.html#the-pipe-1"><i class="fa fa-check"></i><b>22.2</b> The pipe (%&gt;%)</a></li>
<li class="chapter" data-level="22.3" data-path="answers.html"><a href="answers.html#quasiquotation-1"><i class="fa fa-check"></i><b>22.3</b> Quasiquotation</a></li>
<li class="chapter" data-level="22.4" data-path="answers.html"><a href="answers.html#loading-1"><i class="fa fa-check"></i><b>22.4</b> Loading</a></li>
<li class="chapter" data-level="22.5" data-path="answers.html"><a href="answers.html#cleaning-1"><i class="fa fa-check"></i><b>22.5</b> Cleaning</a></li>
<li class="chapter" data-level="22.6" data-path="answers.html"><a href="answers.html#tidying-1"><i class="fa fa-check"></i><b>22.6</b> Tidying</a></li>
<li class="chapter" data-level="22.7" data-path="answers.html"><a href="answers.html#grouping-1"><i class="fa fa-check"></i><b>22.7</b> Grouping</a></li>
<li class="chapter" data-level="22.8" data-path="answers.html"><a href="answers.html#mutating-1"><i class="fa fa-check"></i><b>22.8</b> Mutating</a></li>
<li class="chapter" data-level="22.9" data-path="answers.html"><a href="answers.html#summarising-1"><i class="fa fa-check"></i><b>22.9</b> Summarising</a></li>
<li class="chapter" data-level="22.10" data-path="answers.html"><a href="answers.html#plotting-1"><i class="fa fa-check"></i><b>22.10</b> Plotting</a></li>
<li class="chapter" data-level="22.11" data-path="answers.html"><a href="answers.html#modelling-1"><i class="fa fa-check"></i><b>22.11</b> Modelling</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">opeRate</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelling" class="section level1">
<h1><span class="header-section-number">14</span> Modelling</h1>
<p>This chapter is inspired by the simple and concise explanation presented in Hadley Wickham and Garrett Grolemund’s <a href="https://r4ds.had.co.nz/model-basics.html#model-basics">R for Data Science book</a>.</p>
<p>A model helps us quantify the relationships between variables in a dataset. By understanding these relationships, we can use these models to better understand the data we have, and to make predictions for unseen data.</p>
<p>A relationship can be quantified by two influences:</p>
<ul>
<li>A true pattern</li>
<li>Random error</li>
</ul>
<p>The goal of the model is to identify the true patterns from the random error and noise. As an example, let’s say you’re testing the impact of a new drug on cancer treatment. You have half of your participants take the drug, and the other half take placebo. Then, you want to model the impact of your treatment to see if it actually works. In your data though, you’re going to see changes between the groups that are due to your intervention (your drug), but also some changes that are just due to random influences, like individual differences, measurement errors, whatever it may be. The goal of a model is to strip away these random influences and quantify in its purest from, the relationship between your variables of interest.</p>
<p>In reality, you will never perfectly capture a relationship for two reasons:</p>
<ol style="list-style-type: decimal">
<li>We can never truly strip away the noise.</li>
<li>Perfect relationships don’t really exist.</li>
</ol>
<p>But that’s not really the point. We will never get things spot on, but models can help us with useful approximations that can inform our decision making and further analysis.</p>
<div id="types-of-model" class="section level2">
<h2><span class="header-section-number">14.1</span> Types of model</h2>
<p>Models types usually fall into “families”. These will be a set of models that are underpinned by some common statistics or philosophy. The most common type of model that is taught at beginner level is the linear model. A linear model assumes a relationship that can be represented in the form <code>y = a + a1x...</code>, where <code>a</code> and <code>a1</code> represent coefficients (values that will change between models depending on your data).</p>
<p>In this chapter we’re going to look exclusively at linear models. In the next chapter though, we’ll take a different family of models; neural networks.</p>
<div id="linear-models" class="section level3">
<h3><span class="header-section-number">14.1.1</span> Linear models</h3>
<p>A linear model with the formula <code>y = 8 + (2*x)</code> might look like this:</p>
<p><img src="opeRate_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<p>A model with different coefficients (<code>y = 210 - (10*x)</code>) would look different:</p>
<p><img src="opeRate_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
<p>The first coefficient (<code>a</code>), determines where the line starts on the y value (when x is 0). The other coefficient (<code>a1</code>) determines how quickly the line will go up or down (its gradient) as the values of x increase. Although the value of the coefficients will change, a linear model that uses that formula will always be a straight line.</p>
</div>
<div id="quadratic" class="section level3">
<h3><span class="header-section-number">14.1.2</span> Quadratic</h3>
<p>The linear model also extends to quadratic functions. This is often a source of confusion as quadratic models don’t look ‘linear’. The ‘linear’ in linear model actually refers to the coefficients rather than our regression line being linear.</p>
<p>Quadratic models are expressed by the formula <code>y = a + (a1*x) + (a2*x^2)</code>. We have the same coefficients as our previous linear model, but now a new one (<code>a2</code>) as well. This extra coefficient allows us to quantify non-linear relationships. For example, a quadratic model with the formula <code>y = 10 - (5) + (2*x^2)</code> might look like this:</p>
<p><img src="opeRate_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p>Quadratic models allow us to capture relationships between variables that change with different values of x. Real-life examples of relationships like this include:</p>
<ul>
<li>population growth</li>
<li>appreciation of certain commodities</li>
<li>infection rates</li>
</ul>
<p>We’ll look at how to identify what type of model is more appropriate for your analysis a bit later.</p>
</div>
</div>
<div id="coefficients" class="section level2">
<h2><span class="header-section-number">14.2</span> Coefficients</h2>
<p>In linear modelling, our coefficients are the values that change in our formula to describe our data. In our standard linear model formula (e.g. <code>y = a + a1*x</code>), the two coefficients represent the intercept (<code>a</code>) and the slope (<code>a1</code>). In other words, the <code>a</code> represents the value of <code>y</code> when <code>x</code> is 0 (so where the line would start on the y axis), and <code>a1</code> defines how quickly that line goes up or down (its gradient). There will be values for those two coefficients that will produce a better model that others. For example, let’s create two models to predict the miles per gallon a car will get based on its weight from the <code>mtcars</code> dataset and compare them.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1">mtcars <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb124-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> wt, <span class="dt">y =</span> mpg)) <span class="op">+</span></a>
<a class="sourceLine" id="cb124-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb124-4" title="4"><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">45</span>, <span class="dt">slope =</span> <span class="fl">-6.5</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb124-5" title="5"><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">35</span>, <span class="dt">slope =</span> <span class="dv">-5</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<p>Here we’ve created two models with different coefficient values; one where <code>a = 45</code> and <code>a1 = -6.5</code>, and other where <code>a = 35</code> and <code>a1 = -5</code>. Both seem to represent the data pretty well, but how can we know which of the pair of coefficients is the ‘better’ fit? Similarly, we’ve tried just two sets of values here, how can we find the absolute best coefficient values to create the best model?</p>
</div>
<div id="residuals" class="section level2">
<h2><span class="header-section-number">14.3</span> Residuals</h2>
<p>When we create a model, there will be a difference between the model’s predicted value and each data point. These are the <strong>model residuals</strong>. The smaller the total residual difference, the more accurate the model is. Let’s visualise our residuals for one of our two <code>mtcars</code> models:</p>
<p><img src="opeRate_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>Just from looking at the graph, we can see that most of our predictions are pretty far off. However, we need to boil all of these differences between the predicted and actual values to a single value. This will allow us to easily compare different models. For this we use the <strong>root-mean-square-error</strong> or RMSE. The calculation for this metric is quite easy - calculate the difference between each data point and the model, square it, average them all and then take the root. Let’s write some functions to produce some models and get some predictions, and then compare the RMSE:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1"><span class="co"># Create some models with different coefficients</span></a>
<a class="sourceLine" id="cb125-2" title="2">coefficients &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</a>
<a class="sourceLine" id="cb125-3" title="3">  <span class="dt">id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,</a>
<a class="sourceLine" id="cb125-4" title="4">  <span class="dt">a =</span> <span class="kw">runif</span>(<span class="dv">10</span>, <span class="dt">min =</span> <span class="dv">35</span>, <span class="dt">max =</span> <span class="dv">40</span>),</a>
<a class="sourceLine" id="cb125-5" title="5">  <span class="dt">a1 =</span> <span class="kw">runif</span>(<span class="dv">10</span>, <span class="dt">min =</span> <span class="dv">-6</span>, <span class="dt">max =</span> <span class="dv">-5</span>)</a>
<a class="sourceLine" id="cb125-6" title="6">)</a>
<a class="sourceLine" id="cb125-7" title="7"></a>
<a class="sourceLine" id="cb125-8" title="8"></a>
<a class="sourceLine" id="cb125-9" title="9"><span class="co"># Plot the models</span></a>
<a class="sourceLine" id="cb125-10" title="10"><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> wt, <span class="dt">y =</span> mpg)) <span class="op">+</span></a>
<a class="sourceLine" id="cb125-11" title="11"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb125-12" title="12"><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">data =</span> coefficients,</a>
<a class="sourceLine" id="cb125-13" title="13">              <span class="kw">aes</span>(<span class="dt">intercept =</span> a, <span class="dt">slope =</span> a1, <span class="dt">colour =</span> <span class="kw">as.factor</span>(id)), <span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb125-14" title="14"><span class="st">  </span><span class="kw">scale_colour_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;Model&quot;</span>)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1"><span class="co"># Create a function to represent our model and give us predictions</span></a>
<a class="sourceLine" id="cb126-2" title="2"><span class="co"># a and a1 represent our coefficients</span></a>
<a class="sourceLine" id="cb126-3" title="3">model &lt;-<span class="st"> </span><span class="cf">function</span>(a, a1, wt) {</a>
<a class="sourceLine" id="cb126-4" title="4">  a <span class="op">+</span><span class="st"> </span>(wt <span class="op">*</span><span class="st"> </span>a1)</a>
<a class="sourceLine" id="cb126-5" title="5">}</a>
<a class="sourceLine" id="cb126-6" title="6"></a>
<a class="sourceLine" id="cb126-7" title="7"><span class="co"># Create a function to work out the rmse of our model</span></a>
<a class="sourceLine" id="cb126-8" title="8">rmse &lt;-<span class="st"> </span><span class="cf">function</span>(a, a1, wt, mpg) {</a>
<a class="sourceLine" id="cb126-9" title="9">  <span class="co"># Find the difference between the model value and the actual value</span></a>
<a class="sourceLine" id="cb126-10" title="10">  diff &lt;-<span class="st"> </span><span class="kw">model</span>(a, a1, wt) <span class="op">-</span><span class="st"> </span>mpg</a>
<a class="sourceLine" id="cb126-11" title="11">  <span class="kw">sqrt</span>(<span class="kw">mean</span>(diff <span class="op">^</span><span class="st"> </span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb126-12" title="12">}</a></code></pre></div>
<p>Now we know how to calculate our RMSE, let’s calculate which of our models has the lowest error:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1">best_model &lt;-<span class="st"> </span>coefficients <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb127-2" title="2"><span class="st">  </span><span class="co"># Here we calculate the rmse of each model</span></a>
<a class="sourceLine" id="cb127-3" title="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">mutate</span>(<span class="dt">rmse =</span> <span class="kw">unlist</span>(purrr<span class="op">::</span><span class="kw">map2</span>(<span class="dt">.x =</span> a, <span class="dt">.y =</span> a1, <span class="dt">.f =</span> rmse,</a>
<a class="sourceLine" id="cb127-4" title="4">                                          <span class="dt">wt =</span> mtcars<span class="op">$</span>wt, <span class="dt">mpg =</span> mtcars<span class="op">$</span>mpg))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb127-5" title="5"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(rmse <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(rmse))</a>
<a class="sourceLine" id="cb127-6" title="6"><span class="kw">print</span>(best_model)</a></code></pre></div>
<pre><code>##   id       a        a1     rmse
## 1  8 38.4438 -5.618441 2.973893</code></pre>
<p>According to our analysis, model 8 has the lowest residual error. Let’s see what that model looks like:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" title="1"><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> wt, <span class="dt">y =</span> mpg)) <span class="op">+</span></a>
<a class="sourceLine" id="cb129-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb129-3" title="3"><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">data =</span> best_model,</a>
<a class="sourceLine" id="cb129-4" title="4">              <span class="kw">aes</span>(<span class="dt">intercept =</span> a, <span class="dt">slope =</span> a1, <span class="dt">colour =</span> <span class="kw">as.factor</span>(id)), <span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb129-5" title="5"><span class="st">  </span><span class="kw">scale_colour_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;Model&quot;</span>)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>That looks pretty good, but it’s not perfect. We’ve just tried 10 different sets of values and then chosen the best one. This doesn’t mean that we’ve found the absolute best coefficients for our model. To produce the best model possible, we’d need to work out the best values by <strong>optimising</strong> our RMSE function - finding the values that produce the global minimum RMSE value.</p>
<p>That’s essentially the process that the <code>lm()</code> function in R uses; it automatically finds the best coefficient values by calculating the RMSE for lots of different values and then choosing the best ones.</p>
</div>
<div id="lm" class="section level2">
<h2><span class="header-section-number">14.4</span> <code>lm()</code></h2>
<p>Now that we’ve understood the basics behind a linear model, I can finally reveal that R has a function that will do all of this for us. The <code>lm()</code> function in R just needs the dataset and the formula for our model, and works out the coefficients for us, giving us back a model:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1">lm_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> mtcars, mpg <span class="op">~</span><span class="st"> </span>wt)</a>
<a class="sourceLine" id="cb130-2" title="2"><span class="co"># This formula is equivalent to `y = a + (a1*x)`</span></a>
<a class="sourceLine" id="cb130-3" title="3"><span class="co"># where y = mpg and x = wt</span></a>
<a class="sourceLine" id="cb130-4" title="4">lm_model</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Coefficients:
## (Intercept)           wt  
##      37.285       -5.344</code></pre>
<p>We can see that the <code>lm()</code> function has calculated coefficient values of 37.285 for the intercept, and -5.344 for the slope. We weren’t too far off with 38.44 and -5.62!</p>
<p>To model quadratic relationships with the <code>lm()</code> function, our syntax is a little different:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1"><span class="co"># This formula is equivalent to `y = a + (a1*x) + (a2*x^2)</span></a>
<a class="sourceLine" id="cb132-2" title="2"><span class="kw">lm</span>(<span class="dt">data =</span> mtcars, mpg <span class="op">~</span><span class="st"> </span>wt <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(wt<span class="op">^</span><span class="dv">2</span>))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + I(wt^2), data = mtcars)
## 
## Coefficients:
## (Intercept)           wt      I(wt^2)  
##      49.931      -13.380        1.171</code></pre>
<p><strong>Note:</strong>
The <code>I()</code> bit here tells R to treat what we’ve written (<code>wt^2</code>) as one expression, rather than two (<code>wt</code> &amp; <code>2</code>).</p>
<p>The <code>lm()</code> function returns a linear model object. We’ll take a look at how to evaluate a model in the <a href="modelling.html#evaluating-models">Evaluating Models</a> section.</p>
</div>
<div id="multiple-predictors" class="section level2">
<h2><span class="header-section-number">14.5</span> Multiple Predictors</h2>
<p>So far we’ve focused on the relationship between just two variables. But in reality, you’ll be using multiple variables in your model to better predict your dependent variable. When we introduce additional variables, we can look for <strong>simple</strong> or <strong>interaction</strong> effects.</p>
<div id="simple-effects" class="section level3">
<h3><span class="header-section-number">14.5.1</span> Simple effects</h3>
<p>Simple effects are the additive effects of multiple variables when used to predict a dependent variable. For example, we might want to also introduce the effect of horsepower <code>hp</code> on the miles per gallon of the cars in the <code>mtcars</code> dataset. To do that, we would just add the <code>hp</code> variable to our model:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1"><span class="kw">lm</span>(<span class="dt">data =</span> mtcars, mpg <span class="op">~</span><span class="st"> </span>wt <span class="op">+</span><span class="st"> </span>hp)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + hp, data = mtcars)
## 
## Coefficients:
## (Intercept)           wt           hp  
##    37.22727     -3.87783     -0.03177</code></pre>
<p>We now get coefficient values for each of the variables we provided. This tells us the impact of weight and horsepower separately on the <code>mpg</code> value. In other words, for every increase of 1 in <code>wt</code>, we see a drop of around 4 in <code>mpg</code>, and for every increase of 1 in <code>hp</code>, we see a drop of around 0.03 in <code>mpg</code>. These drops are consistent regardless of the value of either of the variables.</p>
</div>
<div id="interaction-effects" class="section level3">
<h3><span class="header-section-number">14.5.2</span> Interaction effects</h3>
<p>Often however, the variables you’re introducing into your model won’t influence your dependent variable in isolation. Instead, the variables will interact with each other. For example, let’s imagine we’re modelling the impact of the type of food and condiment its served with on customer satisfaction. Those two variables are going to related - it makes a big difference if you serve mustard with fish and chips compared to roast beef! It wouldn’t be appropriate therefore to just identify the relationship between the food and the condiments separately on customer satisfaction. Instead we would to understand how customer satisfaction changes as <em>both</em> the food and the condiment changes.</p>
<p>To add interaction effects to our model, we use the <code>*</code> operator:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1"><span class="kw">lm</span>(<span class="dt">data =</span> mtcars, <span class="dt">formula =</span> mpg <span class="op">~</span><span class="st"> </span>wt <span class="op">*</span><span class="st"> </span>hp)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt * hp, data = mtcars)
## 
## Coefficients:
## (Intercept)           wt           hp        wt:hp  
##    49.80842     -8.21662     -0.12010      0.02785</code></pre>
<p>Now we have 3 coefficients:</p>
<ul>
<li>The impact of <code>wt</code> alone</li>
<li>The impact of <code>hp</code> alone</li>
<li>The impact of <code>wt:hp</code> together</li>
</ul>
<p>We could also write the formula like this <code>mpg ~ wt + hp + wt:hp</code>.</p>
<p>Now we know how to create models using the <code>lm()</code> function, let’s look at how we can better understand and evaluate them.</p>
</div>
</div>
<div id="evaluating-models" class="section level2">
<h2><span class="header-section-number">14.6</span> Evaluating Models</h2>
<p>Jumping straight into modelling a dataset you don’t understand or creating a model that looks good and then declaring that your work is done can be a dangerous thing. Modelling should be a weapon in your data science arsenal, but it should be handled with care. It’s very easy to make an error and end up with a model that is pointless at best and misleading at worst.</p>
<p>To demonstrate this, let’s produce 4 models for the each of the sub-datasets in the <code>anscombe</code> dataset:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1"><span class="co"># Create tidy versions of the datasets</span></a>
<a class="sourceLine" id="cb138-2" title="2">tidy_anscombe &lt;-<span class="st"> </span>anscombe <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb138-3" title="3"><span class="st">  </span>tidyr<span class="op">::</span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(),</a>
<a class="sourceLine" id="cb138-4" title="4">                      <span class="dt">names_to =</span> <span class="kw">c</span>(<span class="st">&quot;.value&quot;</span>, <span class="st">&quot;dataset&quot;</span>),</a>
<a class="sourceLine" id="cb138-5" title="5">                      <span class="dt">names_pattern =</span> <span class="st">&quot;(.)(.)&quot;</span></a>
<a class="sourceLine" id="cb138-6" title="6">  )</a>
<a class="sourceLine" id="cb138-7" title="7"></a>
<a class="sourceLine" id="cb138-8" title="8"><span class="co"># Create a model and get the coefficients for each model</span></a>
<a class="sourceLine" id="cb138-9" title="9">models &lt;-<span class="st"> </span>purrr<span class="op">::</span><span class="kw">map</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="op">~</span>tidy_anscombe <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb138-10" title="10"><span class="st">                       </span>dplyr<span class="op">::</span><span class="kw">filter</span>(dataset <span class="op">==</span><span class="st"> </span>.x) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb138-11" title="11"><span class="st">                       </span><span class="kw">lm</span>(<span class="dt">data =</span> ., <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x)</a>
<a class="sourceLine" id="cb138-12" title="12">)</a>
<a class="sourceLine" id="cb138-13" title="13">purrr<span class="op">::</span><span class="kw">map</span>(models, <span class="op">~</span>.x<span class="op">$</span>coefficients)</a></code></pre></div>
<pre><code>## [[1]]
## (Intercept)           x 
##   3.0000909   0.5000909 
## 
## [[2]]
## (Intercept)           x 
##    3.000909    0.500000 
## 
## [[3]]
## (Intercept)           x 
##   3.0024545   0.4997273 
## 
## [[4]]
## (Intercept)           x 
##   3.0017273   0.4999091</code></pre>
<p>According to our output, we’ve got 4 very similar models. From that output we might assume that the datasets must be very similar. Let’s plot them now:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">tidy_anscombe <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb140-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y  =</span> y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb140-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb140-4" title="4"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb140-5" title="5"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>dataset)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>Now that we’ve looked a little deeper, we can clearly see that these models are inappropriate for three of the four datasets (2, 3 and 4). The lesson here is that there are multiple tools at your disposal when analysing data, and overeliance on a particular tool without due care and attention can cause issues.</p>
<p>With that in mind, let’s look at some ways of evaluating the strength of your model.</p>
<div id="lm-output" class="section level3">
<h3><span class="header-section-number">14.6.1</span> <code>lm()</code> Output</h3>
<p>Now we’ve created a model using the <code>lm()</code> function, let’s understand the output a little bit so we can evaluate our model. When we just print the model, we get the formula we provided, and the coefficients:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" title="1"><span class="kw">print</span>(lm_model)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Coefficients:
## (Intercept)           wt  
##      37.285       -5.344</code></pre>
<p>By using the <code>summary()</code> function, we can find out a little more about our model:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1"><span class="kw">summary</span>(lm_model)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5432 -2.3647 -0.1252  1.4096  6.8727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
## wt           -5.3445     0.5591  -9.559 1.29e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.046 on 30 degrees of freedom
## Multiple R-squared:  0.7528, Adjusted R-squared:  0.7446 
## F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
<p>There’s a lot to unpack here.</p>
<p><strong>Residuals</strong></p>
<p>We’ve now got a residuals section that shows us the range and quartiles of our residuals. This can be helpful to understand whether your model is consistently over or underestimating</p>
<p><strong>Coefficients</strong></p>
<p>We’ve also now got an expanded view of our coefficients. We’ve still got our estimates, but now we’ve also got standard error, t value and then P value entries.</p>
<p><em>Standard error</em></p>
<p>The standard error represents the average difference between the estimated value and the actual value. So for example, our coefficient estimate for <code>wt</code> is roughly -5, meaning that we lose 5 miles per gallon for every increase of 1000 lbs (1 <code>wt</code> unit). Our error value of roughly 0.5 tells us that actually, on average, it’s between -5.5 and -4.5. If our standard error was 2, then that would suggest that on average, an increase in 1 <code>wt</code> unit would correspond with a change of between -7 and -3. A lower standard error value usually represents a more accurate model.</p>
<p><em>t value</em></p>
<p>The t value is then the estimate divided by its error. We can use this value to estimate the strength of our relationship between the two variables; a strong relationship (i.e. a high coefficient value) and a low error will produce a high t value. Conversely, a smaller coefficient value representing a weaker relationship and then a large error value suggesting that we’re struggling to accurately predict the value of y will have a low t value.</p>
<p><em>P value</em></p>
<p>P values are something of a hot topic in statistics so we won’t discuss them in length here. Instead, we’ll focus on exactly what a P value is - not whether it’s a good idea to use one.</p>
<p>A t value is converted to a P value via a T distribution table based on the degrees of freedom (don’t worry about what this is). P values represent how often we would see this same t value if the two variables had absolutely no relationship at all. The larger the t value is (i.e. the stronger the relationship appears to be), the less likely it is that we would observe this relationship purely by chance.
The typically accepted value for considering a relationship to not be the result of chance is 0.05 (i.e. we’d only see these results if there was truly no relationship 1 in 20 times), but that’s more an academic rule of thumb. In reality, you shouldn’t really rely too heavily on the p value to tell you the strength of your model.</p>
<p><strong>Residual standard error</strong></p>
<p>This is the residual standard error of the entire model (as opposed to a single variable). The logic is the same though; it’s the average difference between our model’s estimate and the actual value. This is almost equivalent to the Residual Mean Standard Error we calculated before, but it’s calculated slightly differently.</p>
<p><strong>Multiple &amp; Adjusted R-squared</strong></p>
<p>The R-squared value represents how much of the variance in y can be explained by your model. So we’ve got a Multiple R-Squared value of around 0.7, meaning that 70% of the variance we see in the <code>mpg</code> value can be explained by the effect of <code>wt</code>. The larger the value the better. But if you ever get an R-Squared value of 1, you’ve definitely done something wrong.</p>
<p>If you have one variable, then the Multiple R-Squared value is fine to use. If you have more than 1 though, the Adjusted R-Squared value will account for the fact that you’re going to explain more variance simply by adding more variables, and so tries to correct for that.</p>
<p><strong>F Statistic</strong></p>
<p>The F statistic is a global test for whether any of your coefficients are non-zero (if you have a relationship between any of your variables and the dependent variable). The reason we have this global test is that as you increase the number of variables in our model, you’re increasing the likelihood that at least 1 will have a significant relationship with your dependent variable. We learned before that our rough estimate for considering a ‘true’ relationship is that we would only observe the t value of that size once every 20 times if there was no relationship. Well then if you include 20 variables, you’ll get one significant predictor on average each time. The F value takes this into account and then tells you whether you have at least 1 significant predictor given the number of variables that you tried.</p>
</div>
<div id="residuals-1" class="section level3">
<h3><span class="header-section-number">14.6.2</span> Residuals</h3>
<p>As we’ve learnt previously, the goal of our model is to reduce the total residual difference between our model and the data. But blindly reducing this value without then inspecting the result can be dangerous. When you’re using the <code>lm()</code> function, your residuals should be <strong>normally distributed</strong>. That means that (essentially) your model should be overestimating as much as it’s underestimating for every value of y.</p>
<p>Let’s take a look at the residual values for our <code>mtcars</code> model:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1">mt_residuals &lt;-<span class="st"> </span>mtcars <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb145-2" title="2"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_residuals</span>(<span class="dt">model =</span> <span class="kw">lm</span>(<span class="dt">data =</span> mtcars, <span class="dt">formula =</span> mpg <span class="op">~</span><span class="st"> </span>wt <span class="op">+</span><span class="st"> </span>hp))</a>
<a class="sourceLine" id="cb145-3" title="3"></a>
<a class="sourceLine" id="cb145-4" title="4">mt_residuals <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb145-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> resid)) <span class="op">+</span></a>
<a class="sourceLine" id="cb145-6" title="6"><span class="st">  </span><span class="kw">geom_freqpoly</span>(<span class="dt">binwidth =</span> <span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>Things kind of look okay, but it’s tough to know for sure because have so few estimates. Let’s take a look at how our residuals change for different <code>mpg</code> values:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1">mt_residuals <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb146-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mpg, <span class="dt">y =</span> resid)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb146-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
<p>Here we can see what looks like random noise. This is good because it means that our model isn’t performing better for some values than for others. If it is, that means we have a systematic bias in our model.</p>
<p>Alternatively, let’s compare this plot with a plot of one of the <code>anscombe</code> datasets:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" title="1">tidy_anscombe <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb147-2" title="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(dataset <span class="op">==</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb147-3" title="3"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_residuals</span>(<span class="dt">model =</span> models[[<span class="dv">2</span>]]) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb147-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> resid)) <span class="op">+</span></a>
<a class="sourceLine" id="cb147-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-95-1.png" width="672" /></p>
<p>Here we can see a very clear trend, meaning that our model is not representing the data very well. Instead, it is overestimating and underestimating in a predictable pattern for different values of x. If you see a residual plot like this, something’s gone wrong.</p>
</div>
<div id="overfitting" class="section level3">
<h3><span class="header-section-number">14.6.3</span> Overfitting</h3>
<p>The goal of a model is usually to make a prediction. To be able to make those predictions, we train the model on observed data (i.e. data where we have the values of the independent and dependent variables). However, if we train the model to represent the observed data too well, the model may not perform well on new datasets. We call this <strong>overfitting</strong> - our model represents the test data too well and does not generalise well.</p>
<p>Let’s look at an example of overfitting. We’ll split the <code>mtcars</code> dataset into two; a training set and a test set. We’re purposely going to split our data badly here but in reality you’d split the dataset randomly.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1">train_mtcars &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(mtcars, wt <span class="op">&lt;=</span><span class="st"> </span><span class="fl">3.3</span>)</a>
<a class="sourceLine" id="cb148-2" title="2">test_mtcars &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(mtcars, wt <span class="op">&gt;=</span><span class="st"> </span><span class="fl">3.3</span>)</a></code></pre></div>
<p>Then we’ll train our model on the test set and evaluate the residuals:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" title="1"><span class="co"># This is the same as wt + wt^2 + wt^3 + wt^4 + ... wt^7</span></a>
<a class="sourceLine" id="cb149-2" title="2">overfit_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> train_mtcars, <span class="dt">formula =</span> mpg <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(wt, <span class="dv">7</span>))</a>
<a class="sourceLine" id="cb149-3" title="3"></a>
<a class="sourceLine" id="cb149-4" title="4">train_mtcars <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb149-5" title="5"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_predictions</span>(overfit_model) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb149-6" title="6"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> mpg, <span class="dt">x =</span> wt)) <span class="op">+</span></a>
<a class="sourceLine" id="cb149-7" title="7"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb149-8" title="8"><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> pred))</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1">train_mtcars <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb150-2" title="2"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_residuals</span>(overfit_model) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb150-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> wt, <span class="dt">y =</span> resid)) <span class="op">+</span></a>
<a class="sourceLine" id="cb150-4" title="4"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb150-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-97-2.png" width="672" /></p>
<p>Things seem to look fine. Our residuals look pretty random and we seem to be representing the data we have well. When we then apply the model to our test dataset (data the model wasn’t trained on) however…</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" title="1">test_mtcars <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb151-2" title="2"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_predictions</span>(overfit_model) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb151-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> mpg, <span class="dt">x =</span> wt)) <span class="op">+</span></a>
<a class="sourceLine" id="cb151-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb151-5" title="5"><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> pred))</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
<p>That’s clearly not right at all. We’ve got predictions that are nowhere near the actual values.</p>
<p>What’s happened is our model has overfit the training data, representing noise and randomness as a true relationship between the variables. When we then apply the model to new data then, where that noise is different, it performs terribly.</p>
<p>Let’s compare this with a simpler model that doesn’t overfit.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1">nonoverfit_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> train_mtcars, <span class="dt">formula =</span> mpg <span class="op">~</span><span class="st"> </span>wt)</a>
<a class="sourceLine" id="cb152-2" title="2">test_mtcars <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb152-3" title="3"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_predictions</span>(nonoverfit_model) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb152-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> mpg, <span class="dt">x =</span> wt)) <span class="op">+</span></a>
<a class="sourceLine" id="cb152-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb152-6" title="6"><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> pred))</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-99-1.png" width="672" /></p>
<p>Much better. The model still isn’t perfect, but it’s much better than our previous example even though it’s much less complex.</p>
<div id="avoiding-overfitting" class="section level4">
<h4><span class="header-section-number">14.6.3.1</span> Avoiding overfitting</h4>
<p>Unforunately, there’s no single way to really avoid overfitting. There are things that can be done to mitigate it though:</p>
<ul>
<li>Prefer simplicity
<ul>
<li>Where possible, a simpler model will likely be preferable to a more complex model</li>
</ul></li>
<li>Split your test and training data appropriately
<ul>
<li>In our example, we purposely split the training data badly but in practice you should aim to represent your data equally well in both your training and test datasets.</li>
</ul></li>
<li>Properly evaluate your models
<ul>
<li>By properly evaluating and understanding our model, you should be able to identify and mitigate the effects of overfitting</li>
</ul></li>
</ul>
</div>
</div>
</div>
<div id="video-game-sales-model" class="section level2">
<h2><span class="header-section-number">14.7</span> Video Game Sales Model</h2>
<p>Now we’ve created some example models, let’s apply what we’ve learned to our video games dataset.</p>
<p>Let’s model the effect of year and genre on video game sales between 1980 and 2000:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" title="1">vg_sales_to_model &lt;-<span class="st"> </span>tidy_vg_sales <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-2" title="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(Year <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1980</span> <span class="op">&amp;</span><span class="st"> </span>Year <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2000</span>,</a>
<a class="sourceLine" id="cb153-3" title="3">                Country <span class="op">==</span><span class="st"> &quot;Global&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-4" title="4"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">group_by</span>(Genre, Year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-5" title="5"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">summarise</span>(<span class="dt">Total_Sales =</span> <span class="kw">sum</span>(Sales), <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-6" title="6"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">mutate</span>(<span class="dt">Genre =</span> forcats<span class="op">::</span><span class="kw">fct_lump_n</span>(Genre, <span class="dt">n =</span> <span class="dv">7</span>, <span class="dt">w =</span> Total_Sales)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-7" title="7"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(Genre <span class="op">!=</span><span class="st"> &quot;Other&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-8" title="8"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">group_by</span>(Genre, Year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-9" title="9"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">summarise</span>(<span class="dt">Total_Sales =</span> <span class="kw">sum</span>(Total_Sales), <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>)</a>
<a class="sourceLine" id="cb153-10" title="10"></a>
<a class="sourceLine" id="cb153-11" title="11">vg_sales_to_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb153-12" title="12"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year, <span class="dt">y =</span> Total_Sales)) <span class="op">+</span></a>
<a class="sourceLine" id="cb153-13" title="13"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb153-14" title="14"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>Genre)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-100-1.png" width="672" /></p>
<p>There does seem to be a relationship - we’re seeing more sales as the years increase - but it might not be equal for the different genres. For this reason, let’s create a model that looks at the interaction effects between genre and year:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1">vg_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> vg_sales_to_model, <span class="dt">formula =</span> Total_Sales <span class="op">~</span><span class="st"> </span>Year <span class="op">*</span><span class="st"> </span>Genre)</a></code></pre></div>
<p>Let’s plot a model for each genre model:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" title="1">vg_sales_to_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb155-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year, <span class="dt">y =</span> Total_Sales, <span class="dt">colour =</span> Genre)) <span class="op">+</span></a>
<a class="sourceLine" id="cb155-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb155-4" title="4"><span class="st">  </span><span class="co"># This will produce the same model as we did with the `lm()` model</span></a>
<a class="sourceLine" id="cb155-5" title="5"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x, <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb155-6" title="6"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="ot">NA</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb155-7" title="7"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>Genre)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
<p>From our plot, it looks as though we’re only seeing a different effect of year in a couple of the genres - the role-playing genre seems to have grown at a faster rate than the others, with shooters growing at a slower rate. Let’s compare this to our model summary:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="kw">summary</span>(vg_model)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Total_Sales ~ Year * Genre, data = vg_sales_to_model)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -14.139  -5.391  -1.586   5.334  30.230 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            -2.476e+03  6.403e+02  -3.867 0.000186 ***
## Year                    1.249e+00  3.217e-01   3.883 0.000175 ***
## GenreFighting           1.700e+02  1.084e+03   0.157 0.875656    
## GenrePlatform           8.928e+02  9.407e+02   0.949 0.344602    
## GenreRacing            -6.248e+02  9.957e+02  -0.627 0.531648    
## GenreRole-Playing      -3.077e+03  1.241e+03  -2.479 0.014680 *  
## GenreShooter            2.191e+03  9.055e+02   2.419 0.017162 *  
## GenreSports            -8.449e+02  9.055e+02  -0.933 0.352778    
## Year:GenreFighting     -8.664e-02  5.443e-01  -0.159 0.873805    
## Year:GenrePlatform     -4.455e-01  4.727e-01  -0.943 0.347919    
## Year:GenreRacing        3.130e-01  5.001e-01   0.626 0.532647    
## Year:GenreRole-Playing  1.544e+00  6.231e-01   2.478 0.014693 *  
## Year:GenreShooter      -1.103e+00  4.550e-01  -2.424 0.016969 *  
## Year:GenreSports        4.245e-01  4.550e-01   0.933 0.352896    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.928 on 112 degrees of freedom
## Multiple R-squared:  0.5087, Adjusted R-squared:  0.4517 
## F-statistic: 8.922 on 13 and 112 DF,  p-value: 2.696e-12</code></pre>
<p>This seems to support what we estimated from the plots - there’s definitely a positive effect of year (we’re selling more games as the years go by), and we can see that this effect is different for the Role-Playing and Shooter groups. If we look at the estimate values, we can see that the Shooter genre has a negative value and the Role-Playing genre is positive. This also backs up what we estimated from the plots - the popularity of shooter games has grown more slowly than other genres, whilst the popularity of role-playing games has increased more quickly.</p>
<p>It’s worth noting that when you use a character or factor variable like we have here (<code>Genre</code>), the first level of that variable is used as the base for the model. So we can see that there’s no <code>GenreAction</code> entry in our summary. This is because R has treated that genre as the base (i.e the Intercept value) and then compared the effect of the other levels against that base. So when we say that the popularity of shooter game has grown more slowly, this is compared to the base class (the growth of action games).</p>
<p>Before we call it a day however, let’s evaluate our model residuals. If we look at the residuals of the model specifically for the ‘Action’ genre, they don’t look very random:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1">action_genre_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> vg_sales_to_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb158-2" title="2"><span class="st">                           </span>dplyr<span class="op">::</span><span class="kw">filter</span>(Genre <span class="op">==</span><span class="st"> &quot;Action&quot;</span>), Total_Sales <span class="op">~</span><span class="st"> </span>Year)</a>
<a class="sourceLine" id="cb158-3" title="3">vg_sales_to_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb158-4" title="4"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(Genre <span class="op">==</span><span class="st"> &quot;Action&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb158-5" title="5"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_residuals</span>(action_genre_model) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb158-6" title="6"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year, <span class="dt">y =</span> resid)) <span class="op">+</span></a>
<a class="sourceLine" id="cb158-7" title="7"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb158-8" title="8"><span class="st">  </span><span class="kw">geom_point</span>() </a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-104-1.png" width="672" /></p>
<p>Instead, we’re overestimating closer to the limits of our year range, and underestimating in the middle. This suggests to me that a quadratic model would be more appropriate. Let’s try that:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" title="1">vg_quad_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> vg_sales_to_model, <span class="dt">formula =</span> Total_Sales <span class="op">~</span><span class="st"> </span>Year <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(Year<span class="op">^</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span>Genre <span class="op">+</span><span class="st"> </span>Genre<span class="op">:</span>Year)</a>
<a class="sourceLine" id="cb159-2" title="2"></a>
<a class="sourceLine" id="cb159-3" title="3"></a>
<a class="sourceLine" id="cb159-4" title="4">vg_sales_to_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb159-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year, <span class="dt">y =</span> Total_Sales, <span class="dt">colour =</span> Genre)) <span class="op">+</span></a>
<a class="sourceLine" id="cb159-6" title="6"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb159-7" title="7"><span class="st">  </span><span class="co"># This will produce the same model as we did with the `lm()` model</span></a>
<a class="sourceLine" id="cb159-8" title="8"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(x<span class="op">^</span><span class="dv">2</span>), <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb159-9" title="9"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="ot">NA</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb159-10" title="10"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>Genre)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1"><span class="kw">summary</span>(vg_quad_model)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Total_Sales ~ Year + I(Year^2) + Genre + Genre:Year, 
##     data = vg_sales_to_model)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -15.4608  -5.0524  -0.6718   3.5095  30.5729 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             4.506e+05  9.400e+04   4.794 5.11e-06 ***
## Year                   -4.541e+02  9.447e+01  -4.807 4.84e-06 ***
## I(Year^2)               1.144e-01  2.374e-02   4.820 4.58e-06 ***
## GenreFighting           3.878e+02  9.913e+02   0.391  0.69637    
## GenrePlatform           1.121e+03  8.606e+02   1.303  0.19542    
## GenreRacing            -3.969e+02  9.108e+02  -0.436  0.66384    
## GenreRole-Playing      -1.708e+03  1.169e+03  -1.461  0.14688    
## GenreShooter            2.190e+03  8.271e+02   2.648  0.00927 ** 
## GenreSports            -8.449e+02  8.271e+02  -1.022  0.30923    
## Year:GenreFighting     -1.961e-01  4.977e-01  -0.394  0.69428    
## Year:GenrePlatform     -5.599e-01  4.324e-01  -1.295  0.19802    
## Year:GenreRacing        1.986e-01  4.575e-01   0.434  0.66499    
## Year:GenreRole-Playing  8.577e-01  5.867e-01   1.462  0.14659    
## Year:GenreShooter      -1.103e+00  4.156e-01  -2.653  0.00914 ** 
## Year:GenreSports        4.245e-01  4.156e-01   1.021  0.30935    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.155 on 111 degrees of freedom
## Multiple R-squared:  0.5938, Adjusted R-squared:  0.5425 
## F-statistic: 11.59 on 14 and 111 DF,  p-value: 5.34e-16</code></pre>
<p>This seems to have improved things. We now have a higher t value for our Intercept (representing our Action genre), suggesting that we’ve better captured the relationship between the genre and sales with this new model. When we now look at the interactions, we can see that actually only the shooter genre has a significantly different interaction with Year. In other words, there is no difference in the relationship between Year and Sales between the genres other than if the game is shooter.</p>
<p>Let’s check our residuals again to make sure we’re not still predictably over or underestimating:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" title="1">qd_action_genre_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> vg_sales_to_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb162-2" title="2"><span class="st">                              </span>dplyr<span class="op">::</span><span class="kw">filter</span>(Genre <span class="op">==</span><span class="st"> &quot;Action&quot;</span>), Total_Sales <span class="op">~</span><span class="st"> </span>Year <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(Year<span class="op">^</span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb162-3" title="3">vg_sales_to_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb162-4" title="4"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(Genre <span class="op">==</span><span class="st"> &quot;Action&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb162-5" title="5"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_residuals</span>(qd_action_genre_model) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb162-6" title="6"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year, <span class="dt">y =</span> resid)) <span class="op">+</span></a>
<a class="sourceLine" id="cb162-7" title="7"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb162-8" title="8"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
<p>That looks much more random to me!</p>
<div id="predicting-the-future" class="section level3">
<h3><span class="header-section-number">14.7.1</span> Predicting the future</h3>
<p>This model isn’t that useful alone; we need to do something with it. Let’s use our model to predict what video game sales might look like for Role-Playing games in 20 years time…</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1"><span class="kw">expand.grid</span>(<span class="dt">Year =</span> <span class="dv">2000</span><span class="op">:</span><span class="dv">2040</span>, <span class="dt">Genre =</span> <span class="kw">c</span>(<span class="st">&quot;Action&quot;</span>, <span class="st">&quot;Shooter&quot;</span>, <span class="st">&quot;Role-Playing&quot;</span>, <span class="st">&quot;Fighting&quot;</span>, <span class="st">&quot;Platform&quot;</span>, <span class="st">&quot;Racing&quot;</span>, <span class="st">&quot;Sports&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb163-2" title="2"><span class="st">  </span>modelr<span class="op">::</span><span class="kw">add_predictions</span>(<span class="dt">model =</span> vg_quad_model) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb163-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year, <span class="dt">y =</span> pred, <span class="dt">colour =</span> Genre)) <span class="op">+</span></a>
<a class="sourceLine" id="cb163-4" title="4"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb163-5" title="5"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Predicted Sales (Millions)&quot;</span>)</a></code></pre></div>
<p><img src="opeRate_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<p>As expected, most of our genres are predicted to increase at basically the same rate, with Shooter games still selling more as the years go by, but just at a slower pace.</p>
<p>Hopefully though, this highlights the benefits and drawbacks with using models to predict the future. Here we’ve created a model that can give us testable predictions that we can incorporate into our thoughts and decision-making. The model though, is overly simple, and we’re missing some important but complex variables. For example, how has the rise of video game streaming platforms like Twitch and YouTube Gaming changed video game sales in recent years? And how will this continue to evolve&gt; Modelling effects such as these can be difficult, so it’s best to start off small, create a simple model, then look to improve.</p>
</div>
</div>
<div id="questions-3" class="section level2">
<h2><span class="header-section-number">14.8</span> Questions</h2>
<ol style="list-style-type: decimal">
<li>What’s the difference between <code>y ~ x*w</code> and <code>y ~ x:w</code>?</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="plotting.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="machine-learning.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": [["opeRate.pdf", "PDF"], ["opeRate.mobi", "Kindle EBook"], ["opeRate.epub", "EPUB EBook"]],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
